env:
  browser: true
  es2020: true
extends:
  - "plugin:prettier/recommended"
  - "prettier/@typescript-eslint"
  - "prettier/react"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
overrides:
  - files:
      - "**/*.tsx"
    rules:
      react/prop-types: "off"
